version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: burger
    ports:
      - "9988:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M